name: tabla_didactica_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 0.5.0
  cloud_firestore: "^0.14.0+2"
  path_provider: ^1.6.16
  path: ^1.7.0
  cupertino_icons: ^0.1.3
  email_validator: ^1.0.0
  unicorndial: ^1.1.5
  flutter_tts: ^0.7.0
  page_transition: "^1.1.6"
  google_fonts: ^1.1.0
  loading_overlay: ^0.2.1
  flutter_spinkit: ^4.1.2+1
  splashscreen:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - fonts/

  fonts:
    - family: BalooTammudu2
      fonts:
        - asset: fonts/BalooTammudu2-Regular.ttf
        - asset: fonts/BalooTammudu2-Medium.ttf
        - asset: fonts/BalooTammudu2-SemiBold.ttf
        - asset: fonts/BalooTammudu2-Bold.ttf
        - asset: fonts/BalooTammudu2-ExtraBold.ttf
