name: didactic_table_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  modal_progress_hud:
  animated_widgets: ^1.0.6
  intl: ^0.17.0
  flutter_svg_provider:
  email_validator: ^2.0.1
  flutter_native_splash: ^1.1.8+4
  page_transition: ^1.1.7+6
  barcode_scan: 1.0.0
  flutter_tts:
  carousel_slider: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  assets:
    - images/

flutter_native_splash:
  image: images/icon.png
  color: "f38181"

