name: visual_survey_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit:
  firebase_core:
  cloud_firestore: 2.0.0
  firebase_auth:
  firebase_storage:
  modal_progress_hud:
  flutter_svg_provider:
  email_validator: ^2.0.1
  progress_indicators: ^0.1.5
  image_picker:
  date_format: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/

flutter_native_splash:
  image: images/icon.png
  color: "212121"