name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  modal_progress_hud:
  animated_widgets: ^1.0.6
  intl: ^0.17.0
  flutter_svg_provider:
  email_validator: ^2.0.1
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/icon.png"
  adaptive_icon_background: "images/icon/icon.png"
  adaptive_icon_foreground: "images/icon/icon.png"

flutter_native_splash:
  image: images/icon/icon.png
  color: "4b778d"